// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwugopridureefyyiyss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3dWdvcHJpZHVyZWVmeXlpeXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Mjk5MzgsImV4cCI6MjA2MDIwNTkzOH0.KtdTAznt0ORo3t7-FR4TFrSblGYNNBGL5sz-vV0YNzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);